### ISSUE TITLE
Financial Target
財務目標：今後の収益や利益の目標、投資計画。

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#14]
# 対応内容
- What are the next milestones to be achieved and what funds are needed?
- 次に達成するマイルストーンと必要な資金は？

**Comment by deerman31** [comment]
First year: 30,000 users and $150,000 in revenue; third year: $500,000 in revenue and 100,000 users.

初年度はユーザー数3万人、収益15万ドル。3年目には収益50万ドル、ユーザー数10万を目標。

数字の根拠の説明　by chatgpt
### 1. **ユーザー数の計算**:
   - 2026年と2028年のSolanaのユーザー数は、2023年のユーザー数（450,000人）を基にして、毎年117%（つまり1.17倍）の成長率で計算しました。

   **2026年のユーザー数**:
   \[
   450,000 \times 1.17^3 = 約720,726人
   \]
   
   **2028年のユーザー数**:
   \[
   450,000 \times 1.17^5 = 約986,601人
   \]

### 2. **返金保証サービスを利用するユーザー数**:
   - 返金保証サービスを利用する割合は、2026年では5%、2028年では10%と仮定しました。
   
   **2026年の返金保証サービス利用者数**（5%）:
   \[
   720,726 \times 0.05 = 約36,036人
   \]
   
   **2028年の返金保証サービス利用者数**（10%）:
   \[
   986,601 \times 0.10 = 約98,660人
   \]

### 3. **収益の計算**:
   - 返金保証サービスの手数料は0.5%（0.005）とし、1人あたりの平均取引額を1,000ドルと仮定しました。収益は次の式で計算しています：
   \[
   収益 = 利用者数 \times 取引額 \times 手数料率
   \]

   **2026年の収益**（5%利用の場合）:
   \[
   36,036 \times 1,000 \times 0.005 = 180,181ドル
   \]
   
   **2028年の収益**（10%利用の場合）:
   \[
   98,660 \times 1,000 \times 0.005 = 493,301ドル
   \]

### まとめ:
- **2026年**の返金保証サービス利用者数は**36,036人**で、収益は**180,181ドル**。
- **2028年**の返金保証サービス利用者数は**98,660人**で、収益は**493,301ドル**。

これらの数字は、ユーザー数の成長と返金保証サービスの利用割合、および手数料に基づいて算出されています。
