### ISSUE TITLE
Team
チーム：プロジェクトに関わる主要なメンバーとその役割。

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#15]
# 対応内容
- What abilities and backgrounds do we have on our team?
- What are the reasons why this problem can only be solved by us?
- どんな能力・経歴を持つ人がチームにいるのか？
- この問題が私たちにしか解決できない理由は何か？

**Comment by deerman31** [comment]
世界で最も革新的な大学ランキング（WURI）で8位に入った42 Tokyo校で、1年以上学んでいる学生で構成されています。

It consists of students who have been studying for at least one year at 42 Tokyo schools, ranked 8th in the World's Most Innovative Universities ranking (WURI).

**Comment by deerman31** [comment]
レビュー時に指摘された点を修正しました。

The 42 Tokyo schools, ranked 8th in the World's Most Innovative Universities ranking (WURI), are made up of talented engineers who have been studying for at least one year.
世界で最も革新的な大学ランキング（WURI）で8位に入った42のTokyo校で、1年以上学んでいる優秀なエンジニアで構成されています。
