### ISSUE TITLE
スケジュール

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#25]
# 対応内容
- 10/6までのマイルストーンを考える

**Comment by weijuan82113** [comment]
## 進捗まとめ

### ピッチとデモの作成に関するtodoを洗い出し、進行方向を定める

**デモ作成**

* フロントエンド作成（小関さん）: レイアウトを練ること
* デモバックグランド試作（池田さん）: 機能ごとにissueを立てるのみで大丈夫か？

**ピッチ資料作成** (コンセプト部分)

* ビジョン深掘り
* 真に解決したい課題の深掘り (issueを立てる)
    * 自分の経験を基づく (審査員の興味にも調査)
    * アンケート調査
* 解決策
* ショートディスクリプション (何か作るか一言)

**デモ動画部分**

* 構成、必要なイメージを練る

**3分のプレゼン動画作成**

---

### 9/27マイルストーン① (developer hub)

**デモ作成**

* 試作から洗い出した問題の解決策探索、FBを求める
* フロントエンドレイアウトレビュー

**ピッチ資料作成**

* コンセプトの部分のレビュー

**3分のプレゼン動画作成**

* ピッチのプレゼントレビュー

---
### プロトタイプ完成に向かってやること
**デモ**

* フロントエンド作成: 予測課題！？
* デモバックグランド試作: 予測課題！？

**ピッチ資料作成**

* ピッチレビュー指摘修正
* デモ動画作成 ※必須ではないが、デモのフロントエンド完成によって作成できるか判断

**3分動画作成**

* ピッチのプレゼントレビュー指摘対応

---

### 10/1マイルストーン② (プロトタイプ完成)

**デモ**

* フロントエンドレビュー (完成)
* バックグランド (完成)

**ピッチ資料作成**

* ピッチ (完成)

**3分動画作成**

* プレゼント （完成）
　(ビックとデモ) 

---

### 10/5 (developer hubにて最終レビュー)

* プレゼンの最終レビュー
