### ISSUE TITLE
質問リストをまとめる

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#28]
# 対応内容
- superteamさんに聞かないといけないことをまとめる

### 提出物
- テスト手順を含む製品デモ リンクとは？
- プレゼンテーション リンクはpitch資料でいいのか？
- プロジェクト X アカウントへのリンクは絶対必要なのか？
- (追加リンク) ピッチ デッキとプレゼンテーションリンクとの違いは？
- プロダクトデモ動画のリンクとテスト方法について、何のテスト、誰がテスト、どこでテストするのか？

### ピッチ
- 大きなビジョンをかかげたときの事業拡張性
- Pitchの見本で具体的な数字を多く出しているが、この数字の根拠はどのくらい確かなものにすべきか、出典は必要なのか。
- ロードマップは具体的な数字が必要なのか
- short description, solution, product, system archtecherの内容がかぶってしまう。どう差別化したらいいか
- ビジネスモデルは必要か、収益のイメージは必要か
- financial targetはどれくらい具体的で、現実的である必要があるのか
- solanaの特徴を発揮したかも評価基準なのか
- 壮大なビジョンを掲げる場合、拡大される事業の解像度はどれくらい高くないといけないのか
- 開発中のプロダクトの収益化は必ず必要なのか
- 主要なインフラなので、手数料はとるべきではないと考える
- もし手数料をとる場合、どれくらいとるべきなのか？（他のサービスは？uniswapなどのdefiは？）

### デモ動画
- デモ動画とは具体的になにを、誰に、どのようにつくるのか？
- プロダクトの宣伝みたいな感じ？
- デモ動画の評価ポイントはなんなのか？

### プレゼン動画
- プレゼン動画の具体的な内容は？
- 実際にpitchのスライドを使って話さなければいけないのか？
- 動画をとるだけでは、いいプレゼンができるイメージがわかない
- プレゼン動画を作る上でプロダクトの完成品が必要かどうか。

### プロダクト
- 返金処理が失敗した場合の対処方法

### 開発
- 開発環境の構築について。一般的にスマートコントラクトを開発する場合にどのように環境構築しているのか 
-  ローカルのテストネット , Devnet, Testnetのどれで開発するのが一般的か
- Devnetでairdropの生成制限に引っかかったが簡単に回避する方法はあるのか(DevnetでのSOLの生成は無料ですよね？)
- スマコンかく際にしらないといけないこと（PDA？）
- 学習のおすすめ（チュートリアルなど）

**Comment by tachu2** [comment]
uniswapのようなサービスは手数料で直接利益をえていない
そのかわり、ガバナンストークンを創業者や投資家は多く所持している。

https://docs.uniswap.org/concepts/protocol/fees
https://docs.uniswap.org/concepts/governance/process

**Comment by tachu2** [comment]
## デモ動画
- figmaなどのツールを使う
→提供価値がわかれば何でもいい

**Comment by tachu2** [comment]
## プレゼン動画
- pitchから選別したプレゼン資料をつくる
- プレゼン資料をもとに、プレゼンする

**Comment by deerman31** [comment]
# Pitch
Pitchや開発をスムーズに進めるためには、まずVisionとProblemを明確にすることが重要です。

# Vision
Visionは壮大であるべきとされていますが、現在の問題意識をキャッチーに表現した方が良いでしょう。

# Problem
Problemは、ストーリーを織り交ぜることで、より具体的で想像しやすくするのが効果的です。

# デモ動画
デモ動画は必ずしも完成品である必要はなく、提供価値が伝わるものであれば良いです。
 ＃Pitchとプレゼン資料は別 Pitch用の資料とプレゼンテーション用の資料は別物であり、プレゼン資料の提出が求められています。

# 成果物を動画などに入れ込むか
プレゼン動画においても成果物の完成は必須ではありません。

# 製品の説明書と使い方の動画
説明書と使い方の動画が必要
製品のUIは、説明書がなくても使えるように設計することが望ましいです。

# データの取得　アンケート
Pitchで用いるデータは、アンケートなどを通じて実際の情報を取得する方が説得力が高まります。

**Comment by tachu2** [comment]
- プロダクトデモのリンクとテスト方法
→実際のプロダクトの使い方をドキュメントなどでまとめる
※そもそもドキュメントを見なくても分かる、uiにしたほうがいい

**Comment by t-ozzy** [comment]
<デモ動画必要？>
プレゼン動画の中にモックを動かした動画を入れれたらいい
なくても良い
というか時間制限的にキツい
OR (前回の優勝者)が参考になる

<事業拡張性>
10年かけて成長させる

<マネタイズ>
今は気にしなくても良い
ただ、どこでマネタイズするか具体的にイメージするとより良い

<このサービスの拡張性>
リアルなモノに結びつける時に各国の法的に問題が出てくる
POOLされたモノを運用しだいで色々できそう(タップしたい者が出てくる)
