### ISSUE TITLE
アンケート作成

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#35]
# 対応内容
- アンケートをとってプレゼンに使えるデータを収集する
## アンケート作成の目的
- ナラティブなストーリーを形成したい（具体的な課題の例、解像度をあげる）
→自分たちの体験談でOKそう？
- プロダクトに対するリアクションや感想が欲しい
## アンケート内容
- アンケート
  - 仮想通貨やblockchainに興味ありますか？（五段階評価）
  - なぜ興味がありますか？
  - なぜ興味がないですか？
  - 仮想通貨やblockchainに対するイメージは？
  - ネガティブかポジティブなイメージが五段階評価
  - blockchain上で取引したことがありますか？（仮想通貨やNFTなど）
    - 使っている場合
      - どれくらいの頻度で使いますか？
      - どのようなサービスで使いますか？
      - トークンのやりとりで詐欺に引っかかったり、間違った取引をしたことがありますか？
      - 現在、blockchainのサービス（仮想通貨やnftなど）が一般人が利用してない理由は何だと思いますか？
    - もし使っていない場合
      - なぜ使わないのか
      - 今後使いたいと思うか？
      - 安全に使える仕組みを提供したら（詐欺などの問題が解決）、blockchain上のサービスを使いたいと思いますか？
  - 返金保証サービス（クーリングオフみたいな）を使用して仮想通貨の決済を返金できるなら、使ってみたいと思いますか？

**Comment by deerman31** [comment]
現在、web3のサービスがマスアダプションしてない理由は何だと思いますか？

cryptに詳しい人でもマスアダプションと聞いて、ピンとこない可能性があるので注釈をつけた方が良いかもしれない。
マスアダプション（大衆に使われるか）
など。

**Comment by weijuan82113** [comment]
解像度を上げるために、下記追加質問をしてもよさそう
- もし返金ができるなら、web3でものを購入したいか？

**Comment by t-ozzy** [comment]
個人的な意見ですが、特に記述式の質問が多い、質問の範囲が広いと感じました。

僕の経験ですが、質問の数が多すぎると途中でアンケートの記入をやめてしまうんじゃないかと思います(特に記述式が多いと尚更)

あと、「現在、blockchainのサービス（仮想通貨やnftなど）が一般人が利用してない理由」や「現在、web3のサービスがマスアダプションしてない理由」はサービスを作る前の需要調査なら必要だとは感じますが、僕たちはもう作るサービスが定まっているので、今回は除いてもいいのではないかと思います。
あれば、より詳しい情報を集められますが、よりアンケートを離脱する可能性は高くなると思います。
どっちを取るかはお任せします。

以下自分が整理した質問リスト(日本語がおかしかったらすみません)
1.仮想通貨やblockchainに興味ありますか？（五段階評価　1.全く興味ない~5.とても興味ある）
	
2-1.仮想通貨やblockchainに対するイメージは？(五段階評価 -2.全く良い取り組みだと思わない~2.とても良い取り組みだと思う)
2-2.その評価を選んだのかなぜか、具体的に教えてください(記述　必須)

3-1.仮想通貨やNFTなど、blockchain上で取引したことがありますか？(2択)
3-2-1.取引したことがある人に伺います。どれくらいの頻度で使いますか？(記述/選択式にできるなら選択)
3-2-2.取引したことがある人に伺います。blockchainのサービス上で詐欺に引っかかったり、間違った取引をしたことがありますか？(2択)

3-3-1.取引したことがない人に伺います。これまで使ってない理由があれば教えてください(記述 任意)

(3-3-1をけして、)取引したことがある人、取引したことがない人両方に伺います。仮想通貨やnftなどblockchainのサービスが一般に普及していない理由は何だと思いますか？(記述 任意/必須)

4.現在、blockchainのサービス上で誤った取引をしたとき、返金を保証するサービスはありません。もし返金を保証するサービスができたらより普及すると思いますか？(2択)




以下はリストから除いた質問です。

なぜ興味がありますか？
なぜ興味がないですか？
->興味あるなしを記述するのは難しいです。ブロックチェーンに対するイメージなら記述しやすいと思うので、そちらを記述式にしました。

どのようなサービスで使いますか？
現在、blockchainのサービス（仮想通貨やnftなど）が一般人が利用してない理由は何だと思いますか？
現在、web3のサービスがマスアダプションしてない理由は何だと思いますか？
->離脱率を下げるために除きましたが、入れてもいいと思います。

安全に使える仕組みを提供したら（詐欺などの問題が解決）、blockchain上のサービスを使いたいと思いますか？
もし返金ができるなら、web3でものを購入したいか？
->「返金保証サービス（クーリングオフみたいな）を使用して仮想通貨の決済を返金できるなら、使ってみたいと思いますか？」と似ているため除きました。

**Comment by weijuan82113** [comment]
レビューありがとうございます！
小関さんの意見で解析度が上げて分かりやすかったです。
以下は私のFBです。
小関さんの意見を踏まえてアンケートを作成しようと思います。
作成したアンケートに追加意見がありましたら、FBをお願いします。

> 僕の経験ですが、質問の数が多すぎると途中でアンケートの記入をやめてしまうんじゃないかと思います(特に記述式が多いと尚更)
確かに離脱が考えられますので、下記意見を採用したいと思います。
> あと、「現在、blockchainのサービス（仮想通貨やnftなど）が一般人が利用してない理由」や「現在、web3のサービスがマスアダプションしてない理由」はサービスを作る前の需要調査なら必要だとは感じますが、僕たちはもう作るサービスが定まっているので、今回は除いてもいいのではないかと思います。 あれば、より詳しい情報を集められますが、よりアンケートを離脱する可能性は高くなると思います。 どっちを取るかはお任せします。

「現在、blockchainのサービス（仮想通貨やnftなど）が一般人が利用してない理由」や「現在、web3のサービスがマスアダプションしてない理由」はアンケートの結果を集計で分かるため、アンケートから質問を除きます。しかし、離脱を軽減する方法としてアンケートの目的を周知することが重要ですので、アンケートの目的を追加したいなと思いました。

> 以下はリストから除いた質問です。
> 
> なぜ興味がありますか？ なぜ興味がないですか？ ->興味あるなしを記述するのは難しいです。ブロックチェーンに対するイメージなら記述しやすいと思うので、そちらを記述式にしました。

分かりやすいので同意です。

> どのようなサービスで使いますか？ 現在、blockchainのサービス（仮想通貨やnftなど）が一般人が利用してない理由は何だと思いますか？ 現在、web3のサービスがマスアダプションしてない理由は何だと思いますか？ ->離脱率を下げるために除きましたが、入れてもいいと思います。
除きたいと思います。

> 安全に使える仕組みを提供したら（詐欺などの問題が解決）、blockchain上のサービスを使いたいと思いますか？ もし返金ができるなら、web3でものを購入したいか？ ->「返金保証サービス（クーリングオフみたいな）を使用して仮想通貨の決済を返金できるなら、使ってみたいと思いますか？」と似ているため除きました。

重複に考えられるため、除きます。

---
小関さんが設計したアンケートに関するFB
> 3-3-1.取引したことがない人に伺います。これまで使ってない理由があれば教えてください(記述 任意)

取り引きしたことがない人にもWEB2（ネットショーピング）での購入頻度、もしWEB2での購入体験はWEB３でも実現できるならば、仮想通貨を使えたいと思いますか？のように2問で、取引したことがない理由を明確に問いたいです。

**Comment by weijuan82113** [comment]
FBを踏まえてアンケートを新規作成
以下レビューをお願いします。

## **ブロックチェーン/Web3サービス普及に関するアンケート**

**目的:** ブロックチェーンやWeb3サービスが一般に普及していない理由を調査し、今後のサービス開発や普及戦略に役立てる

---

**質問**

1. 仮想通貨やブロックチェーンに興味ありますか？
- (五段階評価 1.全く興味ない ~ 5.とても興味ある)

2-1. 仮想通貨やブロックチェーンに対するイメージは？

- (五段階評価 -2.全く良い取り組みだと思わない ~ 2.とても良い取り組みだと思う)

2-2. その評価を選んだのはなぜか、具体的に教えてください (必須)

- (記述)

3-1. 仮想通貨やNFTなど、ブロックチェーン上で取引したことがありますか？

- (2択)

3-2-1. 取引したことがある人に伺います。どれくらいの頻度で使いますか？

- ほぼ毎日
- 週に数回
- 月に数回
- 年に数回

3-2-2. 取引したことがある人に伺います。ブロックチェーンのサービス上で詐欺に引っかかったり、間違った取引をしたことがありますか？

- (2択)

3-3-1. 取引したことがない人に伺います。現在WEB2ネットでの取引はどれくらいの頻度で使いますか？

- ほぼ毎日
- 週に数回
- 月に数回
- 年に数回

3-3-2. 取引したことがない人に伺います、WEB2ネットの取引体験はWEB3にも再現できるなら、使用したいと思いますか？

- (2択)

3-3-4. 取引したことがある人、取引したことがない人両方に伺います。仮想通貨やNFTなどブロックチェーンのサービスが一般に普及していない理由は何だと思いますか？ (任意/必須)

- (記述)
1. 現在、ブロックチェーンのサービス上で誤った取引をしたとき、返金を保証するサービスはありません。もし返金を保証するサービスができたらより普及すると思いますか？
- (2択)

---

**ご協力いただきありがとうございます！**

**Comment by deerman31** [comment]
取引したことがない人に伺います。現在WEB2ネットでの取引はどれくらいの頻度で使いますか？

WEB2ネットと言われて、すぐ理解できない人もいるので注釈をつけたほうが良い。
WEB2ネット（amazonや楽天などでの取引）

仮想通貨に詳しくない人もアンケートを書く場合もあります。
なので、専門用語にはできる限り、注釈をつけていったほうが良い。

**Comment by weijuan82113** [comment]
下記前提でアンケートを作成する

【仮説】
トークンの使い道が拡大：
・もし現在使っているサービス（水道、電気、WIFI）など、インフラの使用権はブロックチェンで管理されたら
・もし支払っているネットフリックス、アマゾン料金は仮想通貨で支払えるなら
【課題】
未来は全てのインフラ、サービスがブロックチェンに管理されて、使用権限や支払う料金がトークン化になった場合、トークンの引き渡しに関するセキュリティがとても重要になる
【解決策】
トークンの引き渡しは条件付きで、例えば時間内に戻り戻せる

**Comment by weijuan82113** [comment]
## あなたのデジタルライフをもっと豊かにするために、ご協力をお願いします！

このアンケートは、より安全で便利なデジタルサービスを開発するために、あなたの貴重なご意見を伺うものです。

**1. デジタル通貨や新しい決済方法について、どのように思われますか？**

- これらの新しい方法について、どのくらい興味がありますか？
    - 全く興味がない
    - 少し興味がある
    - 興味がある
    - かなり興味がある
    - とても興味がある
- このような新しい方法について、良いと思うこと、悪いと思うことはありますか？具体的に教えてください。

**2. デジタル通貨やNFTを実際に使ったことはありますか？**

- はい
- いいえ

**2-1. 使ったことがある方へ**

- どれくらいの頻度で使いますか？
    - ほぼ毎日
    - 週に数回
    - 月に数回
    - 年に数回
- なぜこれらのサービスを使うのですか？
    - 投資目的
    - 決済の便利さ
    - 分散型の思想に共感
    - その他（具体的に教えてください）
- これらのサービスを利用する際に、不安に思うことはありますか？

**3. ネットショッピングやネット決済は利用しますか？**

- はい
- いいえ

**3-1. 利用する方へ**

- どれくらいの頻度で使いますか？
    - ほぼ毎日
    - 週に数回
    - 月に数回
    - 年に数回
- なぜネットショッピングやネット決済を利用するのですか？
    - 時間や場所を選ばないから
    - 品物がたくさんあるから
    - 比較検討しやすいから
    - その他（具体的に教えてください）
- ネットショッピングやネット決済で不安に思うことはありますか？

**4. 支払い方法について**

- 支払い方法がもっと自由になったら、嬉しいですか？
- 支払い後でも、一定期間であれば取り消せるような仕組みが必須だと思いますか？
- デジタルでの取引で、何か困った経験はありますか？

**ご協力いただき、誠にありがとうございます。**
あなたの貴重なご意見は、より良いサービス開発に繋がります。


下記リンクはgoogle formとなります
https://docs.google.com/forms/d/e/1FAIpQLSfTxbxTNK5SJRMG3PvfRtevvukTxEym2AzvvpDpCQiun14JSA/viewform?usp=sf_link
