### ISSUE TITLE
froutend開発環境構築

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#43]
# 対応内容
- jsからタイプスクリプトに変更
  - buildの時点でエラーがわかるので、PRなげたときにreviewしやすい
  - github actionsでbuildテストも自動化もできる
  - debugしやすい（jsでバグを見つけるのはしんどい）
- Makefileでビルドの自動化
- linterとformatterの導入
  - 複数人で作業をするさい、各環境のフォーマッターが機能すると差分が増えてしまう
  - チーム内でフォーマットのコーディングルールを統一する

**Comment by deerman31** [comment]
終わったのでcloseします。
