### ISSUE TITLE
デモ動画の流れ

### ISSUE THREAD

**Issue by t-ozzy** [YungTatyu/Jin#47]
流れをメモ書き

**Comment by tachu2** [comment]
## Jin 操作説明デモ動画構成

- **イントロ**
  - **あいさつ**
  - **jinの紹介**
  - **アジェンダ**
  
- **Buyer**
  - **ウォレット接続**
  - **画面構成**
  - **機能**
    - **Add new transaction**
    - **返金処理**
- **Seller**
  - **Sellerの画面構成**
  - **引き出し手続き**

- **クロージング**

**Comment by tozeki722105** [comment]
<Add new transaction>
取引を追加するにはadd new transactionから登録できます
