### ISSUE TITLE
フロントエンドテスト

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#58]
# 対応内容
バグがないか徹底的に確認
　→審査員にバグが見つかれば 減点になる
### テスト項目
- フロントから問題なくトランザクションをおこなえるか
  - 取引追加
    - 不正な値の入力
  - refund処理
  - withdrow処理
- 取引履歴がちゃんと表示されるか

**Comment by rikeda-cloud** [comment]
テスト項目
- [x] Sellerの公開鍵
- [x] 送金額
- [x] 返金期限
- [x] 自由入力欄
- [x] 返金処理
- [x] 引出処理
- [x] 取引履歴一覧(4箇所)

**Comment by rikeda-cloud** [comment]
Sellerの公開鍵のバリデーションは良さそう。
ロジック部分でログインしているアカウントの公開鍵をSellerの公開鍵として入力した際に
どのように対処するか。
対処するならスマートコンストラクタ側

**Comment by rikeda-cloud** [comment]
自由入力欄の文字数制限を100bytes(スマートコンストラクタが許容するbytes数)数制限にすべき。
マルチバイト文字が入力された場合に文字数では弾けない。
署名のコンファーム時に警告してくれているから対応しなくてもいいかも

**Comment by rikeda-cloud** [comment]
取引履歴の一覧時に複数回Buyer<->Sellerを行き来するとrpcの単位時間あたりのリクエスト制限に引っかかる。
mainnetではより緩いリクエスト制限らしいので対応しなくても良さそう。
next.js側で不要なリクエストをしている場合は必要最低限に抑えると良さそう

**Comment by rikeda-cloud** [comment]
引き出し処理時にPDAの残高は
`ユーザーが送金したSOL + PDAを維持するための残高(0.023SOLくらい)`らしく、残高がAmountよりも多い場合にwithdrawに一覧しているが、Amountが小さすぎる場合、0.023SOLよりも小さすぎてwithdrawできないのに表示されてします。
PDAアカウントにis_withdrawフラグをもたせ、フロントエンド側でそのフラグを見て表示するかを判定する処理を追加すれば良さそう

**Comment by rikeda-cloud** [comment]
テスト範囲ではないが、UIで気になる部分

* next.jsのErrorポップアップが画面左下に表示される(アプリケーションの立ち上げ方法を本番環境用にすれば解決する)
```
-DEV := npx next dev
+DEV := npx next build && npx next start
```
* デバッグ用のアラートやコンソール出力の削除
* トランザクション成功時や失敗時の情報が分かりづらい(時間があれば)
* `Enter Amount`の単位を明示したほうが良さそう(SOL単位かlamports単位か)
