### ISSUE TITLE
プロダクトアンケート作成

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#63]
# 対応内容
返金保証サービスについてのアンケートを作成
- 返金保証サービスをつかいたいですか
- どれくらいの手数料（%）なら払いますか

**Comment by weijuan82113** [comment]
かかる手数料（%）の候補がありますか？
下記の手数料は高すぎたと思いますが、どうしましょうか？

・0%の場合
・0.05%の場合
・0.30%の場合
・1%の場合

※上記は、uniswapの手数料

https://academy.binance.com/ja/articles/what-is-uniswap-v4
Uniswap V3では、様々なリスクレベルと取引量に対応するために、複数の複手数料段階（0.05％、0.30％、1.00％）を導入しました。

**Comment by weijuan82113** [comment]
セキュリティに関連する対価は一般消費者が負担できる手数料（対価）を明確する目的に下記アンケートを作成しました、
レビューをお願いします

## Version1

【必須問題】

- より安全な取引環境の向上に料金をお支払いしますか？
例：返金の保証サービス、支払うの透明化、分散化
    - はい
    - いいえ
- セキュリティの担保にご自身の購入金額に対して、どのくらいの割合の手数料が負担できるでしょうか？
    - 0%
    - 0.05%
    - 0.30%
    - 1%
- セキュリティを担保し続けるサービスにサブスクリプションで利用したいですか？
    - 利用したい
    - 利用したくない

【自由回答】

- セキュリティ対策に力を入れてみたいと考えたことがありますか？どんな形、程度で貢献したいですか？
    - **選択肢1：** 全く考えたことがない
    - **選択肢2：** 漠然と興味はあるが、具体的な行動には移せていない
    - **選択肢3：** セキュリティ対策の重要性は認識しているが、専門知識がないため貢献方法が分からない
    - **選択肢4：** セキュリティに関する知識を学び、積極的に貢献したい
    - **選択肢5：** セキュリティ分野で専門的なスキルを活かしたい

**Comment by weijuan82113** [comment]
アンケートの目的を下記に修正したいですが、意見を聞かせてください。

【目的】
セキュリティに関連する対価は一般消費者が負担できる手数料（対価）を明確にしたい

**Comment by weijuan82113** [comment]
### JIN 返金保証サービスのアンケート調査にご協力、ありがとうございます！

この度は、革新的な返金サービス「JIN」にご関心いただき、誠にありがとうございます。

JINは、従来の返金プロセスを革新し、スマートコントラクトでユーザーと販売者の双方にとって安全かつスムーズな取引を実現するための返金サービスをリリースしました。

お客様の返金保証サービスに対するニーズや、JINのサービスに対するご意見を伺うことで、より良いサービスへと改善していくための貴重な情報を得たいと考えております。


### アンケートの目的

JINの返金保証サービスに関するユーザーの意向を把握し、サービスの導入や料金設定を考えております。より良いサービスへと改善していくための貴重な情報を得たいと考えています。


### アンケート項目例

1. **JINの返金保証サービスについて、ご利用を検討されていますか？**
    - はい、非常に興味がある
    - はい、興味がある
    - いや、あまり興味がない
    - いや、全く興味がない
2. **返金保証サービスの手数料として、どの程度の割合であればお支払いいただけますか？**
    - 1%以下
    - 0.30%以下
    - 0.05%以下
    - 0%
    - その他（具体的に：）
3. **返金保証サービスを、固定費でご利用いただくことに関して、どの範囲の料金が妥当と思いますか？**
※SOLの平均トランザクションフィーは0.000005 SOL、1 SOLが2万円だった場合、0.000005 SOLは0.1円
    - **0~50円**
    - **50~100円**
    - **100~200円**
    - **その他**
4. **返金保証サービスを、サブスクリプション形式でご利用いただくことに関して、どのようにお考えですか？**
    - はい、サブスクリプション形式の方が良い
    - いや、都度支払いの形式の方が良い
    - どっちでも構わない
    - その他（具体的に：）
5. **返金保証サービス導入の際の懸念点があれば教えてください。**
    - （自由記述）

**Comment by weijuan82113** [comment]
設問3に関しての固定費の計算は、
一回の消費$50を想定する前提となります。
わかりやすくために、100円〜200円/1ドルの為替レート範囲で日本円に変換

$50→5000円〜20000円の範囲になるため

一回の消費に1%の料金を取ったら、日本円で下記の選択肢になる
 - 0~50円
 - 50~100円
 - 100~200円
 - その他
