### ISSUE TITLE
Market
市場：ターゲット市場や市場の規模についての説明。

### ISSUE THREAD

**Issue by tachu2** [YungTatyu/Jin#7]
# 対応内容
- Which markets to enter?
- Why now?
- 参入する市場はどこか？ なぜ今なのか？

**Comment by deerman31** [comment]
DeFi市場は年率40％成長、2030年には2,310億ドル規模になると予測される。2030年には返金保証サービスも115億ドル規模に成長と予想。

DeFi市場の成長率は出典(https://www.zionmarketresearch.com/report/decentralized-finance-market)
1億ドルはDeFiの市場規模から、返金保証サービスの市場規模が5％と仮定し、試算。

The DeFi market is projected to grow 40% annually to $231 billion by 2030, with money-back guarantee services also expected to grow to $11.5 billion by 2030.

**Comment by deerman31** [comment]
指摘された点を修正

Solanaの取引数は年率２０％成長、2030年には年間400億件になると予測。返金保証サービスの市場規模は27億ドルに成長と予想。

The number of Solana transactions is projected to grow 20% per year to 40 billion per year by 2030. The market for money-back guarantee services is projected to grow to $2.7 billion.
